# Generated by Django 4.1.3 on 2023-04-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('Pedidos', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
