# Generated by Django 4.1.3 on 2023-04-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Telefono',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Pedidos',
            new_name='pedido',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='pizzeria_ventas',
        ),
    ]
