# Generated by Django 4.1.3 on 2023-04-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_rename_apellido_ventas_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
            ],
            options={
                'db_table': 'pizzeria_inventario',
            },
        ),
    ]
