# Generated by Django 4.1.3 on 2023-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='alta_inventario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
